### ISSUE TITLE
add sailsjs framework

### ISSUE THREAD

**Issue by neonleo** [sindresorhus/awesome-nodejs#1138] opened 2021-08-31 07:22 UTC
sailsjs web framework is great for the peoples from PHP codeigniter , Lavarel 
[https://sailsjs.com/](url)

**Comment by sindresorhus** [comment] 2021-08-31 22:16
Duplicate of #1028

**Closed by sindresorhus** 2021-08-31 22:16 UTC

**Comment by neonleo** [comment] 2021-09-09 02:40
> Duplicate of #1028

I have read #998 
> Thanks for the suggestion, but Sails.js is terrible, and also not actively maintained anymore.

But these statement is 2018, already 3 years and manything is changed, sails.js is much improve and actively maintain.
I recommend you check yourself and don't just refer to 3 years old comment.
